#include <unity.h>
#include <stdio.h>
#include <string.h>

#include "ble.h"
#include "ble_frame.h"
#include "dri.h"
#include "wifi_beacon.h"
#include "wifi_frame.h"
#include "wifi_nan.h"
#include "../support/fixtures.h"

// The reference aircraft the ODID encodings are generated for
// (test/tools/gen_odid_fixtures.cpp builds its scenario from the same values):
// a configured aircraft with good telemetry. The values are this test's own -
// a change to the generator's scenario needs a matching change here.

static const char UA_ID[] = "1DRIFT000TEST00001";
static const char OP_ID[] = "TEST-OPERATOR-1";
static const char UA_DESC[] = "DRIFT test fixture";
static const ODID_status_t STATUS = ODID_STATUS_AIRBORNE;
static const double LAT = 47.3566123;
static const double LON = 8.5321456;
static const double ALT_GEO = 500.5;
static const double HEIGHT = 30.5;
static const float DIRECTION = 90.0;
static const double OPERATOR_LAT = 47.3566000;
static const double OPERATOR_LON = 8.5321000;
static const double OPERATOR_ALT_GEO = 500.0;

// Reference encodings (test/fixtures/odid/*.bin, generated by `make fixtures`):
// the expected ODID output for each message type of the reference aircraft.

static ODID_UAS_Data data;

// The source MAC the Wi-Fi NAN frame tests inject - arbitrary but fixed, so
// the expected frames can be built against it.
static const uint8_t WIFI_NAN_MAC[6] = { 0x24, 0x6F, 0x28, 0x10, 0x00, 0x01 };

// Build the reference ODID_UAS_Data exactly as the firmware does on a
// configured device receiving good telemetry.
static void build_reference_data() {
    odid_initUasData(&data);
    dri_populate_identity(&data, UA_ID, OP_ID, UA_DESC);
    dri_update_status(&data, STATUS);
    dri_update_location(&data, LAT, LON, ALT_GEO, HEIGHT, DIRECTION);
    dri_update_operator(&data, OPERATOR_LAT, OPERATOR_LON, OPERATOR_ALT_GEO);
}

void setUp() {
    memset(&data, 0, sizeof(data));
}

// --- Timing guard ---------------------------------------------------------

void test_due_boundary() {
    TEST_ASSERT_FALSE(dri_due(1000, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER));
    TEST_ASSERT_TRUE(dri_due(1000, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1));
}

void test_due_millis_wraparound() {
    TEST_ASSERT_TRUE(dri_due(0xFFFFFFF0, 0xFFFFFFF0 + 100));
    TEST_ASSERT_FALSE(dri_due(0xFFFFFFF0, 0xFFFFFFF0 + 10));
}

void test_pack_due_boundary() {
    TEST_ASSERT_FALSE(dri_pack_due(1000, 1000 + DRI_PACK_INTERVAL));
    TEST_ASSERT_TRUE(dri_pack_due(1000, 1000 + DRI_PACK_INTERVAL + 1));
}

void test_pack_due_millis_wraparound() {
    // UL suffix keeps the arithmetic in unsigned long on every host: the
    // subtraction wraps the same way on 32- and 64-bit builds.
    TEST_ASSERT_TRUE(dri_pack_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 2000UL));
    TEST_ASSERT_FALSE(dri_pack_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 500UL));
}

void test_wifi_beacon_due_boundary() {
    TEST_ASSERT_FALSE(dri_wifi_beacon_due(1000, 1000 + DRI_WIFI_BEACON_INTERVAL));
    TEST_ASSERT_TRUE(dri_wifi_beacon_due(1000, 1000 + DRI_WIFI_BEACON_INTERVAL + 1));
}

void test_wifi_beacon_due_millis_wraparound() {
    TEST_ASSERT_TRUE(dri_wifi_beacon_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 500UL));
    TEST_ASSERT_FALSE(dri_wifi_beacon_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 100UL));
}

void test_wifi_nan_due_boundary() {
    TEST_ASSERT_FALSE(dri_wifi_nan_due(1000, 1000 + DRI_WIFI_NAN_INTERVAL));
    TEST_ASSERT_TRUE(dri_wifi_nan_due(1000, 1000 + DRI_WIFI_NAN_INTERVAL + 1));
}

void test_wifi_nan_due_millis_wraparound() {
    TEST_ASSERT_TRUE(dri_wifi_nan_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 600UL));
    TEST_ASSERT_FALSE(dri_wifi_nan_due(0xFFFFFFF0UL, 0xFFFFFFF0UL + 100UL));
}

// --- Schedule -------------------------------------------------------------

void test_schedule_period_is_25() {
    // 1 s at 40 ms guard interval: 25 slots per cycle.
    TEST_ASSERT_EQUAL(25, DRI_SCHEDULE_PERIOD);
}

void test_counter_next_sequence_and_wrap() {
    uint8_t c = 0;
    for (uint8_t expected = 1; expected <= 25; expected++) {
        c = dri_counter_next(c);
        TEST_ASSERT_EQUAL(expected, c);
    }
    TEST_ASSERT_EQUAL(1, dri_counter_next(c));
}

void test_slot_type_mapping() {
    TEST_ASSERT_EQUAL(DRI_SLOT_BASIC_ID, dri_slot_type(1));
    TEST_ASSERT_EQUAL(DRI_SLOT_SELF_ID, dri_slot_type(2));
    TEST_ASSERT_EQUAL(DRI_SLOT_OPERATOR_ID, dri_slot_type(3));
    TEST_ASSERT_EQUAL(DRI_SLOT_SYSTEM, dri_slot_type(4));
    TEST_ASSERT_EQUAL(DRI_SLOT_LOCATION, dri_slot_type(5));
    TEST_ASSERT_EQUAL(DRI_SLOT_LOCATION, dri_slot_type(25));
}

// --- Byte-exact encodings -------------------------------------------------

// Slurp a reference encoding; every fixture is exactly one ODID message.
static std::string reference(const char *name) {
    std::string data = fixture_read(std::string("odid/") + name + ".bin");
    TEST_ASSERT_FALSE(data.empty());
    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE, data.size());
    return data;
}

void test_encode_slot_matches_reference_bytes() {
    build_reference_data();
    const struct {
        uint8_t schedule;
        const char *name;
    } cases[] = {
        { 1, "basic_id" },
        { 2, "self_id" },
        { 3, "operator_id" },
        { 4, "system" },
        { 5, "location" },
        { 25, "location" },
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        std::string expected = reference(cases[i].name);
        ODID_Message_encoded encoded;
        dri_encode_slot(&data, cases[i].schedule, &encoded);
        char msg[64];
        snprintf(msg, sizeof(msg), "schedule %u", cases[i].schedule);
        TEST_ASSERT_EQUAL_HEX8_ARRAY_MESSAGE((const uint8_t *)expected.data(), encoded.rawData, ODID_MESSAGE_SIZE, msg);
    }
}

void test_message_header_type_and_version() {
    build_reference_data();
    const struct {
        uint8_t schedule;
        uint8_t header; // type << 4 | protocol version 2
    } cases[] = {
        { 1, 0x02 }, // Basic ID
        { 2, 0x32 }, // Self-ID
        { 3, 0x52 }, // Operator ID
        { 4, 0x42 }, // System
        { 5, 0x12 }, // Location/Vector
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        ODID_Message_encoded encoded;
        dri_encode_slot(&data, cases[i].schedule, &encoded);
        TEST_ASSERT_EQUAL_HEX8(cases[i].header, encoded.rawData[0]);
    }
}

void test_service_data_frame() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    uint8_t buf[ODID_MESSAGE_SIZE + 2];
    size_t len = dri_build_service_data(0x2A, &encoded, buf);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, buf[0]); // 0x0D
    TEST_ASSERT_EQUAL_HEX8(0x2A, buf[1]);
    std::string expected = reference("location");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), buf + 2, ODID_MESSAGE_SIZE);
}

void test_service_data_frame_full_payload() {
    // The reference fixtures all end in 0x00 and the output buffer is
    // pre-zeroed, so a truncated copy is invisible against them. A message
    // with no zero bytes at all, built into a 0xAA-prefilled buffer, catches
    // both a truncated copy and an overrun past the frame.
    ODID_Message_encoded enc;
    for (int i = 0; i < ODID_MESSAGE_SIZE; i++)
        enc.rawData[i] = (uint8_t)(0xB0 + i);

    uint8_t buf[ODID_MESSAGE_SIZE + 4];
    memset(buf, 0xAA, sizeof(buf));
    size_t len = dri_build_service_data(0x37, &enc, buf);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0x37, buf[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(enc.rawData, buf + 2, ODID_MESSAGE_SIZE);
    // In particular the message's last byte arrives, and nothing past the
    // frame is touched.
    TEST_ASSERT_EQUAL_HEX8(enc.rawData[ODID_MESSAGE_SIZE - 1],
                           buf[2 + ODID_MESSAGE_SIZE - 1]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, buf[ODID_MESSAGE_SIZE + 2]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, buf[ODID_MESSAGE_SIZE + 3]);
}

// --- Over-the-air advertisement frame --------------------------------------

void test_adv_frame_on_air_constants() {
    // What the ESP32 body puts on the air: the ASTM Remote ID service UUID
    // the advertisement carries the service data under, and the advertising
    // interval in 0.625 ms BLE slots (DRI_INTERVAL == 20 ms -> 32). Both
    // live in the DRIFT_NO_BLE-free seam, so they are pinnable natively.
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, DRI_UUID);
    TEST_ASSERT_EQUAL(32, BLE_ADV_INTERVAL);
}

void test_adv_frame_carries_the_service_data() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    BleAdvFrame frame;
    size_t len = ble_build_adv_frame(0x2A, &encoded, &frame);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, frame.len);
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, frame.uuid);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, frame.data[0]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, frame.data[1]);
    std::string expected = reference("location");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), frame.data + 2,
                                 ODID_MESSAGE_SIZE);
}

void test_adv_frame_full_payload() {
    // Same no-zero-byte discipline as the service-data test above, through
    // the seam ble_send() actually builds its advertisement from (the frame
    // struct is exactly frame-sized; the overrun past it is pinned by the
    // oversized-buffer test, the last byte by this one).
    ODID_Message_encoded enc;
    for (int i = 0; i < ODID_MESSAGE_SIZE; i++)
        enc.rawData[i] = (uint8_t)(0xC0 + i);

    BleAdvFrame frame;
    size_t len = ble_build_adv_frame(0x01, &enc, &frame);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, frame.uuid);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, frame.data[0]);
    TEST_ASSERT_EQUAL_HEX8(0x01, frame.data[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(enc.rawData, frame.data + 2, ODID_MESSAGE_SIZE);
}

// --- Message pack (BLE5 Long Range transport) ------------------------------

// The reference aircraft's pack: header (type 0xF, protocol version 2,
// single-message size 25, count 5) followed by every valid message in the
// vendored builder's order - Basic ID, Location, Self-ID, System, Operator ID
// - each byte-exact against the reference encodings.
void test_build_pack_matches_reference_bytes() {
    build_reference_data();
    uint8_t buf[DRI_PACK_MAX_SIZE];
    int len = dri_build_pack(&data, buf, sizeof(buf));

    TEST_ASSERT_TRUE(len > 0);
    TEST_ASSERT_EQUAL(3 + 5 * ODID_MESSAGE_SIZE, len);
    TEST_ASSERT_EQUAL_HEX8(0xF2, buf[0]);  // (ODID_MESSAGETYPE_PACKED << 4) | 2
    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE, buf[1]);
    TEST_ASSERT_EQUAL(5, buf[2]);

    const char *names[] = { "basic_id", "location", "self_id", "system", "operator_id" };
    for (int i = 0; i < 5; i++) {
        std::string expected = reference(names[i]);
        char msg[64];
        snprintf(msg, sizeof(msg), "pack message %d", i);
        TEST_ASSERT_EQUAL_HEX8_ARRAY_MESSAGE((const uint8_t *)expected.data(),
                                             buf + 3 + i * ODID_MESSAGE_SIZE,
                                             ODID_MESSAGE_SIZE, msg);
    }
}

void test_build_pack_empty_is_rejected() {
    // Nothing valid: the builder refuses an empty pack instead of letting
    // the transport broadcast one.
    odid_initUasData(&data);
    uint8_t buf[DRI_PACK_MAX_SIZE];
    TEST_ASSERT_TRUE(dri_build_pack(&data, buf, sizeof(buf)) <= 0);
}

void test_build_pack_boot_is_location_only() {
    // From power-on the pack carries just the location message (the ODID
    // "unknown" sentinels odid_initUasData() fills in) - exactly what the
    // BT4 schedule's location slots broadcast before any telemetry arrives.
    dri_init(&data, 1000);
    uint8_t buf[DRI_PACK_MAX_SIZE];
    int len = dri_build_pack(&data, buf, sizeof(buf));

    TEST_ASSERT_EQUAL(3 + ODID_MESSAGE_SIZE, len);
    TEST_ASSERT_EQUAL(1, buf[2]);
    TEST_ASSERT_EQUAL_HEX8(0x12, buf[3]);  // location header

    ODID_Message_encoded location;
    dri_encode_slot(&data, 5, &location);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(location.rawData, buf + 3, ODID_MESSAGE_SIZE);
}

void test_build_pack_service_data() {
    build_reference_data();
    uint8_t pack[DRI_PACK_MAX_SIZE];
    int pack_len = dri_build_pack(&data, pack, sizeof(pack));
    TEST_ASSERT_TRUE(pack_len > 0);

    uint8_t buf[DRI_PACK_MAX_SIZE + 2];
    memset(buf, 0xAA, sizeof(buf));
    size_t len = dri_build_pack_service_data(0x2A, pack, pack_len, buf);

    TEST_ASSERT_EQUAL((size_t)pack_len + 2, len);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, buf[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(pack, buf + 2, pack_len);
}

void test_transmit_pack_schedule_and_counters() {
    dri_init(&data, 1000);
    build_reference_data();
    ble_send_reset();

    // Not due until a full DRI_PACK_INTERVAL has elapsed; the pack counter
    // starts at 0 and the BT4 slot schedule is unaffected by the pack path.
    dri_transmit(&data, 1000 + DRI_PACK_INTERVAL);
    TEST_ASSERT_EQUAL(0, ble_pack_send_count);

    dri_transmit(&data, 1000 + DRI_PACK_INTERVAL + 1);
    TEST_ASSERT_EQUAL(1, ble_pack_send_count);
    TEST_ASSERT_EQUAL(0, ble_pack_send_counters[0]);
    TEST_ASSERT_EQUAL(3 + 5 * ODID_MESSAGE_SIZE, ble_pack_send_lens[0]);
    TEST_ASSERT_EQUAL_HEX8(0xF2, ble_pack_send_bytes[0][0]);

    dri_transmit(&data, 1000 + 2 * DRI_PACK_INTERVAL + 2);
    TEST_ASSERT_EQUAL(2, ble_pack_send_count);
    TEST_ASSERT_EQUAL(1, ble_pack_send_counters[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(ble_pack_send_bytes[0], ble_pack_send_bytes[1],
                                 ble_pack_send_lens[0]);
}

void test_transmit_skips_unencodable_pack() {
    // Out-of-range telemetry on an otherwise unconfigured aircraft: the only
    // valid message (location) fails to encode, the pack comes back empty
    // and the transport must stay silent rather than broadcast a truncated
    // pack - mirroring the BT4 slot skip.
    dri_init(&data, 1000);
    data.Location.Direction = 655.35f;  // MAVLink hdg = UINT16_MAX ("unknown")
    ble_send_reset();

    dri_transmit(&data, 1000 + DRI_PACK_INTERVAL + 1);
    TEST_ASSERT_EQUAL(0, ble_pack_send_count);
}

// --- Raw advertising data (what goes on air) --------------------------------

void test_bt4_ad_on_air_bytes() {
    build_reference_data();
    ODID_Message_encoded enc;
    dri_encode_slot(&data, 5, &enc);

    uint8_t ad[BLE_BT4_AD_SIZE + 2];
    memset(ad, 0xAA, sizeof(ad));
    size_t len = ble_build_bt4_ad(0x2A, &enc, ad, sizeof(ad));

    // Complete Service Data AD structure: [0x1E][0x16][FA][FF][service data],
    // exactly filling the 31-byte legacy PDU payload.
    TEST_ASSERT_EQUAL(31, len);
    TEST_ASSERT_EQUAL_HEX8(0x1E, ad[0]);
    TEST_ASSERT_EQUAL_HEX8(0x16, ad[1]);
    TEST_ASSERT_EQUAL_HEX8(0xFA, ad[2]);  // ASTM UUID 0xFFFA, little-endian
    TEST_ASSERT_EQUAL_HEX8(0xFF, ad[3]);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, ad[4]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, ad[5]);
    std::string expected = reference("location");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), ad + 6, ODID_MESSAGE_SIZE);
    TEST_ASSERT_EQUAL_HEX8(0xAA, ad[31]);  // nothing past the AD structure
}

void test_bt5_ad_carries_the_pack() {
    build_reference_data();
    uint8_t pack[DRI_PACK_MAX_SIZE];
    int pack_len = dri_build_pack(&data, pack, sizeof(pack));
    TEST_ASSERT_TRUE(pack_len > 0);

    uint8_t ad[BLE_BT5_AD_SIZE + 2];
    memset(ad, 0xAA, sizeof(ad));
    size_t len = ble_build_bt5_ad(0x2A, pack, pack_len, ad, sizeof(ad));

    TEST_ASSERT_EQUAL((size_t)pack_len + 6, len);
    TEST_ASSERT_EQUAL_HEX8(pack_len + 5, ad[0]);  // AD length: everything after this byte
    TEST_ASSERT_EQUAL_HEX8(0x16, ad[1]);
    TEST_ASSERT_EQUAL_HEX8(0xFA, ad[2]);
    TEST_ASSERT_EQUAL_HEX8(0xFF, ad[3]);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, ad[4]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, ad[5]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(pack, ad + 6, pack_len);
    TEST_ASSERT_EQUAL_HEX8(0xAA, ad[pack_len + 6]);  // nothing past the AD structure
}

void test_bt5_ad_full_payload() {
    // No-zero-byte discipline: a pack with no zero bytes catches a truncated
    // copy through the non-zero tail, and the 0xAA-prefilled oversized
    // buffer catches an overrun past the AD structure.
    uint8_t pack[3 + 2 * ODID_MESSAGE_SIZE];
    for (size_t i = 0; i < sizeof(pack); i++)
        pack[i] = (uint8_t)(0xD0 + (i % 16));

    uint8_t ad[BLE_BT5_AD_SIZE + 2];
    memset(ad, 0xAA, sizeof(ad));
    size_t len = ble_build_bt5_ad(0x01, pack, sizeof(pack), ad, sizeof(ad));

    TEST_ASSERT_EQUAL(sizeof(pack) + 6, len);
    TEST_ASSERT_EQUAL_HEX8(pack[sizeof(pack) - 1], ad[len - 1]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, ad[len]);
}

void test_bt5_ad_rejects_bad_input() {
    uint8_t pack[DRI_PACK_MAX_SIZE];
    memset(pack, 0x55, sizeof(pack));
    uint8_t ad[BLE_BT5_AD_SIZE];

    TEST_ASSERT_EQUAL(0, ble_build_bt5_ad(0, pack, 0, ad, sizeof(ad)));
    TEST_ASSERT_EQUAL(0, ble_build_bt5_ad(0, pack, DRI_PACK_MAX_SIZE + 1, ad, sizeof(ad)));
    TEST_ASSERT_EQUAL(0, ble_build_bt5_ad(0, pack, DRI_PACK_MAX_SIZE, ad, DRI_PACK_MAX_SIZE));
}

void test_ble5_adv_interval_constants() {
    // The BT5 instance repeats the message pack inside the 1 s pack window:
    // 1600 slots of 0.625 ms, with 1200 as the minimum (0.75 x, the spacing
    // production Remote ID modules use for the coded-PHY instance).
    TEST_ASSERT_EQUAL_UINT32(1600, BLE5_ADV_INTERVAL_MAX);
    TEST_ASSERT_EQUAL_UINT32(1200, BLE5_ADV_INTERVAL_MIN);
}

// --- Wi-Fi Beacon transport (vendor IE on the SoftAP) -----------------------

void test_wifi_ie_on_air_constants() {
    // What the ESP32 body puts on the air: a Vendor-Specific Information
    // Element (element id 221) under the ASD-STAN OUI FA:0B:BC with OUI type
    // 0x0D, sized to carry a counter plus a full message pack. Both live in
    // the platform-neutral seam, so they are pinnable natively.
    TEST_ASSERT_EQUAL_HEX8(0xDD, WIFI_IE_ELEMENT_ID);
    TEST_ASSERT_EQUAL_HEX8(0x0D, WIFI_IE_ODID_OUI_TYPE);
    TEST_ASSERT_EQUAL(7 + DRI_PACK_MAX_SIZE, WIFI_IE_MAX_SIZE);
}

void test_wifi_ie_bytes() {
    build_reference_data();
    uint8_t pack[DRI_PACK_MAX_SIZE];
    int pack_len = dri_build_pack(&data, pack, sizeof(pack));
    TEST_ASSERT_TRUE(pack_len > 0);

    uint8_t ie[WIFI_IE_MAX_SIZE + 2];
    memset(ie, 0xAA, sizeof(ie));
    size_t len = wifi_frame_build_vendor_ie(0x2A, pack, pack_len, ie, sizeof(ie));

    // Vendor IE: [0xDD][length][FA 0B BC][0x0D][counter][pack], where length
    // counts every byte after the length field (OUI + OUI type + payload).
    TEST_ASSERT_EQUAL((size_t)pack_len + 7, len);
    TEST_ASSERT_EQUAL_HEX8(0xDD, ie[0]);
    TEST_ASSERT_EQUAL_HEX8(4 + 1 + pack_len, ie[1]);
    TEST_ASSERT_EQUAL_HEX8(0xFA, ie[2]);
    TEST_ASSERT_EQUAL_HEX8(0x0B, ie[3]);
    TEST_ASSERT_EQUAL_HEX8(0xBC, ie[4]);
    TEST_ASSERT_EQUAL_HEX8(0x0D, ie[5]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, ie[6]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(pack, ie + 7, pack_len);
    TEST_ASSERT_EQUAL_HEX8(0xAA, ie[pack_len + 7]);  // nothing past the IE
}

void test_wifi_ie_full_payload() {
    // Same no-zero-byte discipline as the BLE AD tests: a pack with no zero
    // bytes catches a truncated copy through the non-zero tail, and the
    // 0xAA-prefilled oversized buffer catches an overrun past the IE.
    uint8_t pack[3 + 2 * ODID_MESSAGE_SIZE];
    for (size_t i = 0; i < sizeof(pack); i++)
        pack[i] = (uint8_t)(0xE0 + (i % 16));

    uint8_t ie[WIFI_IE_MAX_SIZE + 2];
    memset(ie, 0xAA, sizeof(ie));
    size_t len = wifi_frame_build_vendor_ie(0x01, pack, sizeof(pack), ie, sizeof(ie));

    TEST_ASSERT_EQUAL(sizeof(pack) + 7, len);
    TEST_ASSERT_EQUAL_HEX8(pack[sizeof(pack) - 1], ie[len - 1]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, ie[len]);
}

void test_wifi_ie_rejects_bad_input() {
    uint8_t pack[DRI_PACK_MAX_SIZE];
    memset(pack, 0x55, sizeof(pack));
    uint8_t ie[WIFI_IE_MAX_SIZE];

    TEST_ASSERT_EQUAL(0, wifi_frame_build_vendor_ie(0, pack, 0, ie, sizeof(ie)));
    TEST_ASSERT_EQUAL(0, wifi_frame_build_vendor_ie(0, pack, DRI_PACK_MAX_SIZE + 1, ie, sizeof(ie)));
    TEST_ASSERT_EQUAL(0, wifi_frame_build_vendor_ie(0, pack, DRI_PACK_MAX_SIZE, ie, DRI_PACK_MAX_SIZE));
}

void test_wifi_ie_matches_vendored_beacon_frame() {
    // Cross-validation against the reference encoder: the vendor IE the
    // vendored odid_wifi_build_message_pack_beacon_frame() embeds in a
    // beacon frame must be byte-identical to wifi_frame_build_vendor_ie()
    // output, so DRIFT's IE cannot drift from the reference implementation.
    build_reference_data();
    uint8_t pack[DRI_PACK_MAX_SIZE];
    int pack_len = dri_build_pack(&data, pack, sizeof(pack));
    TEST_ASSERT_TRUE(pack_len > 0);

    uint8_t mac[6] = { 0x24, 0x6F, 0x28, 0x10, 0x00, 0x01 };
    uint8_t frame[512];
    int frame_len = odid_wifi_build_message_pack_beacon_frame(
        &data, (const char *)mac, "DRIFT", 5, 100, 0x2A, frame, sizeof(frame));
    TEST_ASSERT_TRUE(frame_len > 0);

    // Locate the vendor IE inside the beacon frame: the first element id
    // 0xDD followed by the ASD-STAN OUI and OUI type (the SSID and rates
    // IEs ahead of it are ASCII and fixed bytes, so no false positive).
    int offset = -1;
    for (int i = 0; i + 6 < frame_len; i++) {
        if (frame[i] == 0xDD && frame[i + 2] == 0xFA && frame[i + 3] == 0x0B
            && frame[i + 4] == 0xBC && frame[i + 5] == 0x0D) {
            offset = i;
            break;
        }
    }
    TEST_ASSERT_TRUE(offset >= 0);

    // The IE is the frame's last element: its own length byte must account
    // for exactly the bytes to the end of the frame.
    TEST_ASSERT_EQUAL(frame_len - offset - 2, frame[offset + 1]);

    uint8_t ie[WIFI_IE_MAX_SIZE];
    size_t ie_len = wifi_frame_build_vendor_ie(0x2A, pack, pack_len, ie, sizeof(ie));
    TEST_ASSERT_EQUAL((size_t)(frame_len - offset), ie_len);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(frame + offset, ie, ie_len);
}

void test_transmit_wifi_beacon_schedule_and_counters() {
    dri_init(&data, 1000);
    build_reference_data();
    ble_send_reset();
    wifi_beacon_send_reset();

    // Not due until a full DRI_WIFI_BEACON_INTERVAL has elapsed; the Wi-Fi
    // beacon counter starts at 0.
    dri_transmit(&data, 1000 + DRI_WIFI_BEACON_INTERVAL);
    TEST_ASSERT_EQUAL(0, wifi_beacon_send_count);

    dri_transmit(&data, 1000 + DRI_WIFI_BEACON_INTERVAL + 1);
    TEST_ASSERT_EQUAL(1, wifi_beacon_send_count);
    TEST_ASSERT_EQUAL(0, wifi_beacon_send_counters[0]);
    TEST_ASSERT_EQUAL(3 + 5 * ODID_MESSAGE_SIZE, wifi_beacon_send_lens[0]);
    TEST_ASSERT_EQUAL_HEX8(0xF2, wifi_beacon_send_bytes[0][0]);

    // The Wi-Fi beacon cadence is independent of the BT5 pack schedule: one
    // clock tick past both intervals each transport fires with its own
    // counter.
    dri_transmit(&data, 1000 + DRI_PACK_INTERVAL + 1);
    TEST_ASSERT_EQUAL(2, wifi_beacon_send_count);
    TEST_ASSERT_EQUAL(1, wifi_beacon_send_counters[1]);
    TEST_ASSERT_EQUAL(1, ble_pack_send_count);
    TEST_ASSERT_EQUAL(0, ble_pack_send_counters[0]);

    dri_transmit(&data, 1000 + DRI_PACK_INTERVAL + DRI_WIFI_BEACON_INTERVAL + 2);
    TEST_ASSERT_EQUAL(3, wifi_beacon_send_count);
    TEST_ASSERT_EQUAL(2, wifi_beacon_send_counters[2]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(wifi_beacon_send_bytes[0], wifi_beacon_send_bytes[2],
                                 wifi_beacon_send_lens[0]);
}

void test_transmit_skips_unencodable_wifi_beacon_pack() {
    // Same rejection as the BT5 pack: out-of-range telemetry on an otherwise
    // unconfigured aircraft leaves nothing valid to encode, the pack comes
    // back empty and the Wi-Fi Beacon IE must stay unregistered rather than
    // go out empty.
    dri_init(&data, 1000);
    data.Location.Direction = 655.35f;  // MAVLink hdg = UINT16_MAX ("unknown")
    ble_send_reset();
    wifi_beacon_send_reset();

    dri_transmit(&data, 1000 + DRI_WIFI_BEACON_INTERVAL + 1);
    TEST_ASSERT_EQUAL(0, wifi_beacon_send_count);
}

// --- Wi-Fi NAN transport (raw 802.11 injection on the SoftAP) ---------------

void test_wifi_nan_on_air_constants() {
    // The NAN discovery window period (16 TU x 32) and the frame layouts the
    // vendored builders emit: a 72-byte sync beacon (mgmt header, beacon
    // fields, vendor IE, master indication + cluster + service id list
    // attributes) and an action frame of a fixed 51-byte tail around
    // the message pack.
    TEST_ASSERT_EQUAL(512, DRI_WIFI_NAN_INTERVAL);
    TEST_ASSERT_EQUAL(72, 24 + 12 + 6 + 5 + 16 + 9);
    TEST_ASSERT_EQUAL(51, WIFI_NAN_FRAME_FIXED_SIZE);
    TEST_ASSERT_EQUAL(51 + DRI_PACK_MAX_SIZE, WIFI_NAN_FRAME_MAX_SIZE);
}

void test_transmit_wifi_nan_frames_match_vendored_builders() {
    // The transport injects the vendored encoder's frames verbatim; the
    // action frame is deterministic, so it must be byte-exact against the
    // builder called with the same data, MAC and counter.
    dri_init(&data, 1000);
    build_reference_data();
    wifi_nan_send_reset();
    wifi_nan_init(false, WIFI_NAN_MAC);

    dri_transmit(&data, 1000 + DRI_WIFI_NAN_INTERVAL + 1);
    TEST_ASSERT_EQUAL(1, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(1, wifi_nan_action_send_count);

    uint8_t expected[WIFI_NAN_FRAME_MAX_SIZE];
    int expected_len = odid_wifi_build_message_pack_nan_action_frame(
        &data, (const char *)WIFI_NAN_MAC, 0, expected, sizeof(expected));
    TEST_ASSERT_TRUE(expected_len > 0);
    TEST_ASSERT_EQUAL(expected_len, wifi_nan_action_send_lens[0]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, wifi_nan_action_send_bytes[0], expected_len);

    // The sync beacon carries a CLOCK_MONOTONIC timestamp (bytes 24-31):
    // everything around the timestamp is byte-exact against the builder.
    expected_len = odid_wifi_build_nan_sync_beacon_frame(
        (const char *)WIFI_NAN_MAC, expected, sizeof(expected));
    TEST_ASSERT_TRUE(expected_len > 0);
    TEST_ASSERT_EQUAL(expected_len, wifi_nan_sync_send_lens[0]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, wifi_nan_sync_send_bytes[0], 24);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(expected + 32, wifi_nan_sync_send_bytes[0] + 32,
                                 expected_len - 32);
}

void test_transmit_wifi_nan_schedule_and_counters() {
    dri_init(&data, 1000);
    build_reference_data();
    wifi_nan_send_reset();

    // Not due until a full DRI_WIFI_NAN_INTERVAL has elapsed; both frame types go
    // out together every discovery window, the action counter starting at 0.
    dri_transmit(&data, 1000 + DRI_WIFI_NAN_INTERVAL);
    TEST_ASSERT_EQUAL(0, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(0, wifi_nan_action_send_count);

    dri_transmit(&data, 1000 + DRI_WIFI_NAN_INTERVAL + 1);
    TEST_ASSERT_EQUAL(1, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(1, wifi_nan_action_send_count);
    // The action frame's message counter rides the service info byte at
    // offset 43 (mgmt header + NAN service discovery + service descriptor
    // attribute).
    TEST_ASSERT_EQUAL_HEX8(0, wifi_nan_action_send_bytes[0][43]);

    // One clock tick later nothing is due again.
    dri_transmit(&data, 1000 + DRI_WIFI_NAN_INTERVAL + 2);
    TEST_ASSERT_EQUAL(1, wifi_nan_sync_send_count);

    // The second discovery window increments the counter, which also rides
    // the service descriptor extension attribute at the frame's end
    // (service_update_indicator, the receiver's duplicate detector).
    dri_transmit(&data, 1000 + 2 * DRI_WIFI_NAN_INTERVAL + 2);
    TEST_ASSERT_EQUAL(2, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(2, wifi_nan_action_send_count);
    TEST_ASSERT_EQUAL_HEX8(1, wifi_nan_action_send_bytes[1][43]);
    TEST_ASSERT_EQUAL_HEX8(wifi_nan_action_send_bytes[1][43],
                           wifi_nan_action_send_bytes[1][wifi_nan_action_send_lens[1] - 1]);
}

void test_transmit_skips_unencodable_wifi_nan_action_frame() {
    // Out-of-range telemetry leaves nothing encodable: the action frame is
    // skipped rather than broadcast with an empty pack, while the sync
    // beacon - which carries no ODID data - still goes out. The counter only
    // advances on a transmitted frame, so the next good frame reuses 0.
    dri_init(&data, 1000);
    data.Location.Direction = 655.35f;  // MAVLink hdg = UINT16_MAX ("unknown")
    wifi_nan_send_reset();

    dri_transmit(&data, 1000 + DRI_WIFI_NAN_INTERVAL + 1);
    TEST_ASSERT_EQUAL(1, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(0, wifi_nan_action_send_count);

    dri_update_location(&data, LAT, LON, ALT_GEO, HEIGHT, INV_DIR);
    dri_transmit(&data, 1000 + 2 * DRI_WIFI_NAN_INTERVAL + 2);
    TEST_ASSERT_EQUAL(2, wifi_nan_sync_send_count);
    TEST_ASSERT_EQUAL(1, wifi_nan_action_send_count);
    TEST_ASSERT_EQUAL_HEX8(0, wifi_nan_action_send_bytes[0][43]);
}

// --- Identity population --------------------------------------------------

void test_populate_identity_sets_fields() {
    odid_initUasData(&data);
    dri_populate_identity(&data, UA_ID, OP_ID, UA_DESC);
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(UA_ID, data.BasicID[0].UASID);
    TEST_ASSERT_EQUAL(ODID_OPERATOR_ID, data.OperatorID.OperatorIdType);
    TEST_ASSERT_EQUAL_STRING(OP_ID, data.OperatorID.OperatorId);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(UA_DESC, data.SelfID.Desc);
}

void test_populate_identity_sets_valid_flags() {
    // The message pack is composed from the *Valid flags: an accepted field
    // must mark its message valid, a rejected one must not.
    odid_initUasData(&data);
    dri_populate_identity(&data, UA_ID, OP_ID, UA_DESC);
    TEST_ASSERT_EQUAL(1, data.BasicIDValid[0]);
    TEST_ASSERT_EQUAL(1, data.OperatorIDValid);
    TEST_ASSERT_EQUAL(1, data.SelfIDValid);

    odid_initUasData(&data);
    dri_populate_identity(&data, "", "", "");
    TEST_ASSERT_EQUAL(0, data.BasicIDValid[0]);
    TEST_ASSERT_EQUAL(0, data.OperatorIDValid);
    TEST_ASSERT_EQUAL(0, data.SelfIDValid);
}

void test_populate_identity_empty_strings_leave_defaults() {
    odid_initUasData(&data);
    dri_populate_identity(&data, "", "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_NONE, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL('\0', data.BasicID[0].UASID[0]);
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
    TEST_ASSERT_EQUAL('\0', data.SelfID.Desc[0]);
}

void test_populate_identity_overlong_strings_ignored() {
    odid_initUasData(&data);
    char too_long_id[ODID_ID_SIZE + 2];
    memset(too_long_id, 'X', sizeof(too_long_id) - 1);
    too_long_id[sizeof(too_long_id) - 1] = '\0';
    dri_populate_identity(&data, too_long_id, "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_NONE, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL('\0', data.BasicID[0].UASID[0]);
}

void test_populate_identity_overlong_op_id_ignored() {
    odid_initUasData(&data);
    char too_long[ODID_ID_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, "", too_long, "");
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
}

void test_populate_identity_overlong_ua_desc_ignored() {
    odid_initUasData(&data);
    char too_long[ODID_STR_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, "", "", too_long);
    TEST_ASSERT_EQUAL('\0', data.SelfID.Desc[0]);
}

void test_populate_identity_max_length_strings() {
    odid_initUasData(&data);
    char max_id[ODID_ID_SIZE + 1];
    memset(max_id, 'Y', ODID_ID_SIZE);
    max_id[ODID_ID_SIZE] = '\0';
    dri_populate_identity(&data, max_id, "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(max_id, data.BasicID[0].UASID);
}

void test_populate_identity_max_length_op_id_and_desc() {
    odid_initUasData(&data);
    char max_op_id[ODID_ID_SIZE + 1];
    memset(max_op_id, 'O', ODID_ID_SIZE);
    max_op_id[ODID_ID_SIZE] = '\0';
    char max_desc[ODID_STR_SIZE + 1];
    memset(max_desc, 'D', ODID_STR_SIZE);
    max_desc[ODID_STR_SIZE] = '\0';
    dri_populate_identity(&data, "", max_op_id, max_desc);
    TEST_ASSERT_EQUAL(ODID_OPERATOR_ID, data.OperatorID.OperatorIdType);
    TEST_ASSERT_EQUAL_STRING(max_op_id, data.OperatorID.OperatorId);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(max_desc, data.SelfID.Desc);
}

void test_populate_identity_fields_are_independent() {
    // A rejected field must not affect the others: valid ua_id + overlong
    // op_id + valid ua_desc.
    odid_initUasData(&data);
    char too_long[ODID_ID_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, UA_ID, too_long, UA_DESC);
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(UA_ID, data.BasicID[0].UASID);
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(UA_DESC, data.SelfID.Desc);
}

// --- Dynamic state setters ------------------------------------------------

void test_update_setters() {
    odid_initUasData(&data);
    dri_update_status(&data, STATUS);
    dri_update_location(&data, LAT, LON, ALT_GEO, HEIGHT, DIRECTION);
    dri_update_operator(&data, OPERATOR_LAT, OPERATOR_LON, OPERATOR_ALT_GEO);

    TEST_ASSERT_EQUAL(ODID_STATUS_AIRBORNE, data.Location.Status);
    TEST_ASSERT_EQUAL_DOUBLE(LAT, data.Location.Latitude);
    TEST_ASSERT_EQUAL_DOUBLE(LON, data.Location.Longitude);
    TEST_ASSERT_EQUAL_DOUBLE(ALT_GEO, data.Location.AltitudeGeo);
    TEST_ASSERT_EQUAL(ODID_HEIGHT_REF_OVER_TAKEOFF, data.Location.HeightType);
    TEST_ASSERT_EQUAL_DOUBLE(HEIGHT, data.Location.Height);
    TEST_ASSERT_EQUAL_FLOAT(DIRECTION, data.Location.Direction);

    TEST_ASSERT_EQUAL(ODID_OPERATOR_LOCATION_TYPE_TAKEOFF, data.System.OperatorLocationType);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_LAT, data.System.OperatorLatitude);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_LON, data.System.OperatorLongitude);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_ALT_GEO, data.System.OperatorAltitudeGeo);

    // The dynamic setters mark their messages valid for the message pack.
    TEST_ASSERT_EQUAL(1, data.LocationValid);
    TEST_ASSERT_EQUAL(1, data.SystemValid);
}

// --- Encoder rejection of out-of-range data --------------------------------

// The vendored opendroneid encoder validates its input and returns ODID_FAIL
// without writing the message. Out-of-range telemetry (garbled MAVLink or
// MAVLink's own "unknown" sentinels, e.g. hdg = UINT16_MAX) must therefore
// never surface as a broadcast all-zero message.

void test_encode_slot_rejects_out_of_range_direction() {
    build_reference_data();
    data.Location.Direction = 655.35f;  // MAVLink hdg = UINT16_MAX ("unknown")

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_rejects_out_of_range_height() {
    build_reference_data();
    data.Location.Height = 2147483.75f;  // relative_alt near INT32_MAX / 1000

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_rejects_out_of_range_altitude() {
    build_reference_data();
    data.Location.AltitudeGeo = 2147483.75f;

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_unknown_sentinels_encode() {
    // The ODID "unknown" sentinels (Direction = INV_DIR, Height/AltitudeGeo
    // = INV_ALT) are spec-valid: the encoder accepts them, unlike the raw
    // out-of-range values (previous test). This is what main.cpp's range
    // guards downgrade out-of-range telemetry to.
    build_reference_data();
    data.Location.Direction = INV_DIR;
    data.Location.AltitudeGeo = INV_ALT;
    data.Location.Height = INV_ALT;

    ODID_Message_encoded encoded;
    TEST_ASSERT_TRUE(dri_encode_slot(&data, 5, &encoded));
    std::string expected = reference("location_unknown");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), encoded.rawData, ODID_MESSAGE_SIZE);
}

// --- dri_transmit ------------------------------------------------------------

void test_transmit_gating_schedule_and_counters() {
    dri_init(&data, 1000);
    build_reference_data();
    ble_send_reset();

    // Guard interval (DRI_INTERVAL * DRI_GUARD_MULTIPLIER = 40 ms) not yet
    // elapsed: nothing is broadcast, the schedule does not advance.
    dri_transmit(&data, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER);
    TEST_ASSERT_EQUAL(0, ble_send_count);

    // Due: the first scheduled slot (Basic ID) goes out, counter starts at 0.
    dri_transmit(&data, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1);
    TEST_ASSERT_EQUAL(1, ble_send_count);
    TEST_ASSERT_EQUAL(0, ble_send_counters[0]);
    TEST_ASSERT_EQUAL_HEX8(0x02, ble_send_messages[0].rawData[0]);

    // Run to the end of the 25-slot cycle plus the wrap slot.
    unsigned long now = 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1;
    for (int i = 0; i < 100 && ble_send_count < 26; i++)
        dri_transmit(&data, now += 100);

    TEST_ASSERT_EQUAL(26, ble_send_count);
    // The schedule wrapped back to the Basic ID slot; the message counter
    // incremented once per emitted message.
    TEST_ASSERT_EQUAL_HEX8(0x02, ble_send_messages[25].rawData[0]);
    TEST_ASSERT_EQUAL(25, ble_send_counters[25]);
    for (int i = 1; i < 26; i++)
        TEST_ASSERT_EQUAL(ble_send_counters[i - 1] + 1, ble_send_counters[i]);
}

void test_transmit_skips_unencodable_slot() {
    // Direction out of the ODID range: every location slot (21 per 25-slot
    // cycle) is skipped - not broadcast as a pre-zeroed message - while the
    // schedule keeps rotating and the identity/system slots still go out.
    dri_init(&data, 1000);
    build_reference_data();
    data.Location.Direction = 655.35f;
    ble_send_reset();

    unsigned long now = 1000;
    for (int i = 0; i < 50; i++)  // two full 25-slot cycles
        dri_transmit(&data, now += 100);

    // Two cycles * four identity/system slots; no location message emitted.
    TEST_ASSERT_EQUAL(8, ble_send_count);
    for (int i = 0; i < 8; i++)
        TEST_ASSERT_NOT_EQUAL(ODID_MESSAGETYPE_LOCATION, ble_send_messages[i].rawData[0] >> 4);
    for (int i = 1; i < 8; i++)
        TEST_ASSERT_EQUAL(ble_send_counters[i - 1] + 1, ble_send_counters[i]);
}

// --- Decode round trip ----------------------------------------------------

void test_encode_decode_round_trip() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    ODID_Location_data decoded;
    TEST_ASSERT_EQUAL(0, decodeLocationMessage(&decoded, (ODID_Location_encoded *)&encoded));
    TEST_ASSERT_EQUAL(ODID_STATUS_AIRBORNE, decoded.Status);
    TEST_ASSERT_DOUBLE_WITHIN(1e-6, LAT, decoded.Latitude);
    TEST_ASSERT_DOUBLE_WITHIN(1e-6, LON, decoded.Longitude);
    TEST_ASSERT_FLOAT_WITHIN(0.5f, ALT_GEO, decoded.AltitudeGeo);
    TEST_ASSERT_FLOAT_WITHIN(0.5f, HEIGHT, decoded.Height);
    TEST_ASSERT_FLOAT_WITHIN(1.0f, DIRECTION, decoded.Direction);
}

int main(int, char **) {
    UNITY_BEGIN();
    RUN_TEST(test_due_boundary);
    RUN_TEST(test_due_millis_wraparound);
    RUN_TEST(test_pack_due_boundary);
    RUN_TEST(test_pack_due_millis_wraparound);
    RUN_TEST(test_wifi_beacon_due_boundary);
    RUN_TEST(test_wifi_beacon_due_millis_wraparound);
    RUN_TEST(test_wifi_nan_due_boundary);
    RUN_TEST(test_wifi_nan_due_millis_wraparound);
    RUN_TEST(test_schedule_period_is_25);
    RUN_TEST(test_counter_next_sequence_and_wrap);
    RUN_TEST(test_slot_type_mapping);
    RUN_TEST(test_encode_slot_matches_reference_bytes);
    RUN_TEST(test_message_header_type_and_version);
    RUN_TEST(test_service_data_frame);
    RUN_TEST(test_service_data_frame_full_payload);
    RUN_TEST(test_adv_frame_on_air_constants);
    RUN_TEST(test_adv_frame_carries_the_service_data);
    RUN_TEST(test_adv_frame_full_payload);
    RUN_TEST(test_build_pack_matches_reference_bytes);
    RUN_TEST(test_build_pack_empty_is_rejected);
    RUN_TEST(test_build_pack_boot_is_location_only);
    RUN_TEST(test_build_pack_service_data);
    RUN_TEST(test_transmit_pack_schedule_and_counters);
    RUN_TEST(test_transmit_skips_unencodable_pack);
    RUN_TEST(test_bt4_ad_on_air_bytes);
    RUN_TEST(test_bt5_ad_carries_the_pack);
    RUN_TEST(test_bt5_ad_full_payload);
    RUN_TEST(test_bt5_ad_rejects_bad_input);
    RUN_TEST(test_ble5_adv_interval_constants);
    RUN_TEST(test_wifi_ie_on_air_constants);
    RUN_TEST(test_wifi_ie_bytes);
    RUN_TEST(test_wifi_ie_full_payload);
    RUN_TEST(test_wifi_ie_rejects_bad_input);
    RUN_TEST(test_wifi_ie_matches_vendored_beacon_frame);
    RUN_TEST(test_transmit_wifi_beacon_schedule_and_counters);
    RUN_TEST(test_transmit_skips_unencodable_wifi_beacon_pack);
    RUN_TEST(test_wifi_nan_on_air_constants);
    RUN_TEST(test_transmit_wifi_nan_frames_match_vendored_builders);
    RUN_TEST(test_transmit_wifi_nan_schedule_and_counters);
    RUN_TEST(test_transmit_skips_unencodable_wifi_nan_action_frame);
    RUN_TEST(test_populate_identity_sets_fields);
    RUN_TEST(test_populate_identity_sets_valid_flags);
    RUN_TEST(test_populate_identity_empty_strings_leave_defaults);
    RUN_TEST(test_populate_identity_overlong_strings_ignored);
    RUN_TEST(test_populate_identity_overlong_op_id_ignored);
    RUN_TEST(test_populate_identity_overlong_ua_desc_ignored);
    RUN_TEST(test_populate_identity_max_length_strings);
    RUN_TEST(test_populate_identity_max_length_op_id_and_desc);
    RUN_TEST(test_populate_identity_fields_are_independent);
    RUN_TEST(test_update_setters);
    RUN_TEST(test_encode_slot_rejects_out_of_range_direction);
    RUN_TEST(test_encode_slot_rejects_out_of_range_height);
    RUN_TEST(test_encode_slot_rejects_out_of_range_altitude);
    RUN_TEST(test_encode_slot_unknown_sentinels_encode);
    RUN_TEST(test_transmit_gating_schedule_and_counters);
    RUN_TEST(test_transmit_skips_unencodable_slot);
    RUN_TEST(test_encode_decode_round_trip);
    return UNITY_END();
}
