#include <unity.h>
#include <stdio.h>
#include <string.h>

#include "ble.h"
#include "ble_frame.h"
#include "dri.h"
#include "../support/fixtures.h"

// The reference aircraft the ODID encodings are generated for
// (test/tools/gen_odid_fixtures.cpp builds its scenario from the same values):
// a configured aircraft with good telemetry. The values are this test's own -
// a change to the generator's scenario needs a matching change here.

static const char UA_ID[] = "1DRIFT000TEST00001";
static const char OP_ID[] = "TEST-OPERATOR-1";
static const char UA_DESC[] = "DRIFT test fixture";
static const ODID_status_t STATUS = ODID_STATUS_AIRBORNE;
static const double LAT = 47.3566123;
static const double LON = 8.5321456;
static const double ALT_GEO = 500.5;
static const double HEIGHT = 30.5;
static const float DIRECTION = 90.0;
static const double OPERATOR_LAT = 47.3566000;
static const double OPERATOR_LON = 8.5321000;
static const double OPERATOR_ALT_GEO = 500.0;

// Reference encodings (test/fixtures/odid/*.bin, generated by `make fixtures`):
// the expected ODID output for each message type of the reference aircraft.

static ODID_UAS_Data data;

// Build the reference ODID_UAS_Data exactly as the firmware does on a
// configured device receiving good telemetry.
static void build_reference_data() {
    odid_initUasData(&data);
    dri_populate_identity(&data, UA_ID, OP_ID, UA_DESC);
    dri_update_status(&data, STATUS);
    dri_update_location(&data, LAT, LON, ALT_GEO, HEIGHT, DIRECTION);
    dri_update_operator(&data, OPERATOR_LAT, OPERATOR_LON, OPERATOR_ALT_GEO);
}

void setUp() {
    memset(&data, 0, sizeof(data));
}

// --- Timing guard ---------------------------------------------------------

void test_due_boundary() {
    TEST_ASSERT_FALSE(dri_due(1000, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER));
    TEST_ASSERT_TRUE(dri_due(1000, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1));
}

void test_due_millis_wraparound() {
    TEST_ASSERT_TRUE(dri_due(0xFFFFFFF0, 0xFFFFFFF0 + 100));
    TEST_ASSERT_FALSE(dri_due(0xFFFFFFF0, 0xFFFFFFF0 + 10));
}

// --- Schedule -------------------------------------------------------------

void test_schedule_period_is_25() {
    // 1 s at 40 ms guard interval: 25 slots per cycle.
    TEST_ASSERT_EQUAL(25, DRI_SCHEDULE_PERIOD);
}

void test_counter_next_sequence_and_wrap() {
    uint8_t c = 0;
    for (uint8_t expected = 1; expected <= 25; expected++) {
        c = dri_counter_next(c);
        TEST_ASSERT_EQUAL(expected, c);
    }
    TEST_ASSERT_EQUAL(1, dri_counter_next(c));
}

void test_slot_type_mapping() {
    TEST_ASSERT_EQUAL(DRI_SLOT_BASIC_ID, dri_slot_type(1));
    TEST_ASSERT_EQUAL(DRI_SLOT_SELF_ID, dri_slot_type(2));
    TEST_ASSERT_EQUAL(DRI_SLOT_OPERATOR_ID, dri_slot_type(3));
    TEST_ASSERT_EQUAL(DRI_SLOT_SYSTEM, dri_slot_type(4));
    TEST_ASSERT_EQUAL(DRI_SLOT_LOCATION, dri_slot_type(5));
    TEST_ASSERT_EQUAL(DRI_SLOT_LOCATION, dri_slot_type(25));
}

// --- Byte-exact encodings -------------------------------------------------

// Slurp a reference encoding; every fixture is exactly one ODID message.
static std::string reference(const char *name) {
    std::string data = fixture_read(std::string("odid/") + name + ".bin");
    TEST_ASSERT_FALSE(data.empty());
    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE, data.size());
    return data;
}

void test_encode_slot_matches_reference_bytes() {
    build_reference_data();
    const struct {
        uint8_t schedule;
        const char *name;
    } cases[] = {
        { 1, "basic_id" },
        { 2, "self_id" },
        { 3, "operator_id" },
        { 4, "system" },
        { 5, "location" },
        { 25, "location" },
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        std::string expected = reference(cases[i].name);
        ODID_Message_encoded encoded;
        dri_encode_slot(&data, cases[i].schedule, &encoded);
        char msg[64];
        snprintf(msg, sizeof(msg), "schedule %u", cases[i].schedule);
        TEST_ASSERT_EQUAL_HEX8_ARRAY_MESSAGE((const uint8_t *)expected.data(), encoded.rawData, ODID_MESSAGE_SIZE, msg);
    }
}

void test_message_header_type_and_version() {
    build_reference_data();
    const struct {
        uint8_t schedule;
        uint8_t header; // type << 4 | protocol version 2
    } cases[] = {
        { 1, 0x02 }, // Basic ID
        { 2, 0x32 }, // Self-ID
        { 3, 0x52 }, // Operator ID
        { 4, 0x42 }, // System
        { 5, 0x12 }, // Location/Vector
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        ODID_Message_encoded encoded;
        dri_encode_slot(&data, cases[i].schedule, &encoded);
        TEST_ASSERT_EQUAL_HEX8(cases[i].header, encoded.rawData[0]);
    }
}

void test_service_data_frame() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    uint8_t buf[ODID_MESSAGE_SIZE + 2];
    size_t len = dri_build_service_data(0x2A, &encoded, buf);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, buf[0]); // 0x0D
    TEST_ASSERT_EQUAL_HEX8(0x2A, buf[1]);
    std::string expected = reference("location");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), buf + 2, ODID_MESSAGE_SIZE);
}

void test_service_data_frame_full_payload() {
    // The reference fixtures all end in 0x00 and the output buffer is
    // pre-zeroed, so a truncated copy is invisible against them. A message
    // with no zero bytes at all, built into a 0xAA-prefilled buffer, catches
    // both a truncated copy and an overrun past the frame.
    ODID_Message_encoded enc;
    for (int i = 0; i < ODID_MESSAGE_SIZE; i++)
        enc.rawData[i] = (uint8_t)(0xB0 + i);

    uint8_t buf[ODID_MESSAGE_SIZE + 4];
    memset(buf, 0xAA, sizeof(buf));
    size_t len = dri_build_service_data(0x37, &enc, buf);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0x37, buf[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(enc.rawData, buf + 2, ODID_MESSAGE_SIZE);
    // In particular the message's last byte arrives, and nothing past the
    // frame is touched.
    TEST_ASSERT_EQUAL_HEX8(enc.rawData[ODID_MESSAGE_SIZE - 1],
                           buf[2 + ODID_MESSAGE_SIZE - 1]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, buf[ODID_MESSAGE_SIZE + 2]);
    TEST_ASSERT_EQUAL_HEX8(0xAA, buf[ODID_MESSAGE_SIZE + 3]);
}

// --- Over-the-air advertisement frame --------------------------------------

void test_adv_frame_on_air_constants() {
    // What the ESP32 body puts on the air: the ASTM Remote ID service UUID
    // the advertisement carries the service data under, and the advertising
    // interval in 0.625 ms BLE slots (DRI_INTERVAL == 20 ms -> 32). Both
    // live in the DRIFT_NO_BLE-free seam, so they are pinnable natively.
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, DRI_UUID);
    TEST_ASSERT_EQUAL(32, BLE_ADV_INTERVAL);
}

void test_adv_frame_carries_the_service_data() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    BleAdvFrame frame;
    size_t len = ble_build_adv_frame(0x2A, &encoded, &frame);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, frame.len);
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, frame.uuid);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, frame.data[0]);
    TEST_ASSERT_EQUAL_HEX8(0x2A, frame.data[1]);
    std::string expected = reference("location");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), frame.data + 2,
                                 ODID_MESSAGE_SIZE);
}

void test_adv_frame_full_payload() {
    // Same no-zero-byte discipline as the service-data test above, through
    // the seam ble_send() actually builds its advertisement from (the frame
    // struct is exactly frame-sized; the overrun past it is pinned by the
    // oversized-buffer test, the last byte by this one).
    ODID_Message_encoded enc;
    for (int i = 0; i < ODID_MESSAGE_SIZE; i++)
        enc.rawData[i] = (uint8_t)(0xC0 + i);

    BleAdvFrame frame;
    size_t len = ble_build_adv_frame(0x01, &enc, &frame);

    TEST_ASSERT_EQUAL(ODID_MESSAGE_SIZE + 2, len);
    TEST_ASSERT_EQUAL_HEX16(0xFFFA, frame.uuid);
    TEST_ASSERT_EQUAL_HEX8(DRI_APP_CODE, frame.data[0]);
    TEST_ASSERT_EQUAL_HEX8(0x01, frame.data[1]);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(enc.rawData, frame.data + 2, ODID_MESSAGE_SIZE);
}

// --- Identity population --------------------------------------------------

void test_populate_identity_sets_fields() {
    odid_initUasData(&data);
    dri_populate_identity(&data, UA_ID, OP_ID, UA_DESC);
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(UA_ID, data.BasicID[0].UASID);
    TEST_ASSERT_EQUAL(ODID_OPERATOR_ID, data.OperatorID.OperatorIdType);
    TEST_ASSERT_EQUAL_STRING(OP_ID, data.OperatorID.OperatorId);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(UA_DESC, data.SelfID.Desc);
}

void test_populate_identity_empty_strings_leave_defaults() {
    odid_initUasData(&data);
    dri_populate_identity(&data, "", "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_NONE, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL('\0', data.BasicID[0].UASID[0]);
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
    TEST_ASSERT_EQUAL('\0', data.SelfID.Desc[0]);
}

void test_populate_identity_overlong_strings_ignored() {
    odid_initUasData(&data);
    char too_long_id[ODID_ID_SIZE + 2];
    memset(too_long_id, 'X', sizeof(too_long_id) - 1);
    too_long_id[sizeof(too_long_id) - 1] = '\0';
    dri_populate_identity(&data, too_long_id, "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_NONE, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL('\0', data.BasicID[0].UASID[0]);
}

void test_populate_identity_overlong_op_id_ignored() {
    odid_initUasData(&data);
    char too_long[ODID_ID_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, "", too_long, "");
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
}

void test_populate_identity_overlong_ua_desc_ignored() {
    odid_initUasData(&data);
    char too_long[ODID_STR_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, "", "", too_long);
    TEST_ASSERT_EQUAL('\0', data.SelfID.Desc[0]);
}

void test_populate_identity_max_length_strings() {
    odid_initUasData(&data);
    char max_id[ODID_ID_SIZE + 1];
    memset(max_id, 'Y', ODID_ID_SIZE);
    max_id[ODID_ID_SIZE] = '\0';
    dri_populate_identity(&data, max_id, "", "");
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(max_id, data.BasicID[0].UASID);
}

void test_populate_identity_max_length_op_id_and_desc() {
    odid_initUasData(&data);
    char max_op_id[ODID_ID_SIZE + 1];
    memset(max_op_id, 'O', ODID_ID_SIZE);
    max_op_id[ODID_ID_SIZE] = '\0';
    char max_desc[ODID_STR_SIZE + 1];
    memset(max_desc, 'D', ODID_STR_SIZE);
    max_desc[ODID_STR_SIZE] = '\0';
    dri_populate_identity(&data, "", max_op_id, max_desc);
    TEST_ASSERT_EQUAL(ODID_OPERATOR_ID, data.OperatorID.OperatorIdType);
    TEST_ASSERT_EQUAL_STRING(max_op_id, data.OperatorID.OperatorId);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(max_desc, data.SelfID.Desc);
}

void test_populate_identity_fields_are_independent() {
    // A rejected field must not affect the others: valid ua_id + overlong
    // op_id + valid ua_desc.
    odid_initUasData(&data);
    char too_long[ODID_ID_SIZE + 2];
    memset(too_long, 'X', sizeof(too_long) - 1);
    too_long[sizeof(too_long) - 1] = '\0';
    dri_populate_identity(&data, UA_ID, too_long, UA_DESC);
    TEST_ASSERT_EQUAL(ODID_IDTYPE_SERIAL_NUMBER, data.BasicID[0].IDType);
    TEST_ASSERT_EQUAL_STRING(UA_ID, data.BasicID[0].UASID);
    TEST_ASSERT_EQUAL('\0', data.OperatorID.OperatorId[0]);
    TEST_ASSERT_EQUAL(ODID_DESC_TYPE_TEXT, data.SelfID.DescType);
    TEST_ASSERT_EQUAL_STRING(UA_DESC, data.SelfID.Desc);
}

// --- Dynamic state setters ------------------------------------------------

void test_update_setters() {
    odid_initUasData(&data);
    dri_update_status(&data, STATUS);
    dri_update_location(&data, LAT, LON, ALT_GEO, HEIGHT, DIRECTION);
    dri_update_operator(&data, OPERATOR_LAT, OPERATOR_LON, OPERATOR_ALT_GEO);

    TEST_ASSERT_EQUAL(ODID_STATUS_AIRBORNE, data.Location.Status);
    TEST_ASSERT_EQUAL_DOUBLE(LAT, data.Location.Latitude);
    TEST_ASSERT_EQUAL_DOUBLE(LON, data.Location.Longitude);
    TEST_ASSERT_EQUAL_DOUBLE(ALT_GEO, data.Location.AltitudeGeo);
    TEST_ASSERT_EQUAL(ODID_HEIGHT_REF_OVER_TAKEOFF, data.Location.HeightType);
    TEST_ASSERT_EQUAL_DOUBLE(HEIGHT, data.Location.Height);
    TEST_ASSERT_EQUAL_FLOAT(DIRECTION, data.Location.Direction);

    TEST_ASSERT_EQUAL(ODID_OPERATOR_LOCATION_TYPE_TAKEOFF, data.System.OperatorLocationType);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_LAT, data.System.OperatorLatitude);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_LON, data.System.OperatorLongitude);
    TEST_ASSERT_EQUAL_DOUBLE(OPERATOR_ALT_GEO, data.System.OperatorAltitudeGeo);
}

// --- Encoder rejection of out-of-range data --------------------------------

// The vendored opendroneid encoder validates its input and returns ODID_FAIL
// without writing the message. Out-of-range telemetry (garbled MAVLink or
// MAVLink's own "unknown" sentinels, e.g. hdg = UINT16_MAX) must therefore
// never surface as a broadcast all-zero message.

void test_encode_slot_rejects_out_of_range_direction() {
    build_reference_data();
    data.Location.Direction = 655.35f;  // MAVLink hdg = UINT16_MAX ("unknown")

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_rejects_out_of_range_height() {
    build_reference_data();
    data.Location.Height = 2147483.75f;  // relative_alt near INT32_MAX / 1000

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_rejects_out_of_range_altitude() {
    build_reference_data();
    data.Location.AltitudeGeo = 2147483.75f;

    ODID_Message_encoded encoded;
    TEST_ASSERT_FALSE(dri_encode_slot(&data, 5, &encoded));
}

void test_encode_slot_unknown_sentinels_encode() {
    // The ODID "unknown" sentinels (Direction = INV_DIR, Height/AltitudeGeo
    // = INV_ALT) are spec-valid: the encoder accepts them, unlike the raw
    // out-of-range values (previous test). This is what main.cpp's range
    // guards downgrade out-of-range telemetry to.
    build_reference_data();
    data.Location.Direction = INV_DIR;
    data.Location.AltitudeGeo = INV_ALT;
    data.Location.Height = INV_ALT;

    ODID_Message_encoded encoded;
    TEST_ASSERT_TRUE(dri_encode_slot(&data, 5, &encoded));
    std::string expected = reference("location_unknown");
    TEST_ASSERT_EQUAL_HEX8_ARRAY((const uint8_t *)expected.data(), encoded.rawData, ODID_MESSAGE_SIZE);
}

// --- dri_transmit ------------------------------------------------------------

void test_transmit_gating_schedule_and_counters() {
    dri_init(&data, 1000);
    build_reference_data();
    ble_send_reset();

    // Guard interval (DRI_INTERVAL * DRI_GUARD_MULTIPLIER = 40 ms) not yet
    // elapsed: nothing is broadcast, the schedule does not advance.
    dri_transmit(&data, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER);
    TEST_ASSERT_EQUAL(0, ble_send_count);

    // Due: the first scheduled slot (Basic ID) goes out, counter starts at 0.
    dri_transmit(&data, 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1);
    TEST_ASSERT_EQUAL(1, ble_send_count);
    TEST_ASSERT_EQUAL(0, ble_send_counters[0]);
    TEST_ASSERT_EQUAL_HEX8(0x02, ble_send_messages[0].rawData[0]);

    // Run to the end of the 25-slot cycle plus the wrap slot.
    unsigned long now = 1000 + DRI_INTERVAL * DRI_GUARD_MULTIPLIER + 1;
    for (int i = 0; i < 100 && ble_send_count < 26; i++)
        dri_transmit(&data, now += 100);

    TEST_ASSERT_EQUAL(26, ble_send_count);
    // The schedule wrapped back to the Basic ID slot; the message counter
    // incremented once per emitted message.
    TEST_ASSERT_EQUAL_HEX8(0x02, ble_send_messages[25].rawData[0]);
    TEST_ASSERT_EQUAL(25, ble_send_counters[25]);
    for (int i = 1; i < 26; i++)
        TEST_ASSERT_EQUAL(ble_send_counters[i - 1] + 1, ble_send_counters[i]);
}

void test_transmit_skips_unencodable_slot() {
    // Direction out of the ODID range: every location slot (21 per 25-slot
    // cycle) is skipped - not broadcast as a pre-zeroed message - while the
    // schedule keeps rotating and the identity/system slots still go out.
    dri_init(&data, 1000);
    build_reference_data();
    data.Location.Direction = 655.35f;
    ble_send_reset();

    unsigned long now = 1000;
    for (int i = 0; i < 50; i++)  // two full 25-slot cycles
        dri_transmit(&data, now += 100);

    // Two cycles * four identity/system slots; no location message emitted.
    TEST_ASSERT_EQUAL(8, ble_send_count);
    for (int i = 0; i < 8; i++)
        TEST_ASSERT_NOT_EQUAL(ODID_MESSAGETYPE_LOCATION, ble_send_messages[i].rawData[0] >> 4);
    for (int i = 1; i < 8; i++)
        TEST_ASSERT_EQUAL(ble_send_counters[i - 1] + 1, ble_send_counters[i]);
}

// --- Decode round trip ----------------------------------------------------

void test_encode_decode_round_trip() {
    build_reference_data();
    ODID_Message_encoded encoded;
    dri_encode_slot(&data, 5, &encoded);

    ODID_Location_data decoded;
    TEST_ASSERT_EQUAL(0, decodeLocationMessage(&decoded, (ODID_Location_encoded *)&encoded));
    TEST_ASSERT_EQUAL(ODID_STATUS_AIRBORNE, decoded.Status);
    TEST_ASSERT_DOUBLE_WITHIN(1e-6, LAT, decoded.Latitude);
    TEST_ASSERT_DOUBLE_WITHIN(1e-6, LON, decoded.Longitude);
    TEST_ASSERT_FLOAT_WITHIN(0.5f, ALT_GEO, decoded.AltitudeGeo);
    TEST_ASSERT_FLOAT_WITHIN(0.5f, HEIGHT, decoded.Height);
    TEST_ASSERT_FLOAT_WITHIN(1.0f, DIRECTION, decoded.Direction);
}

int main(int, char **) {
    UNITY_BEGIN();
    RUN_TEST(test_due_boundary);
    RUN_TEST(test_due_millis_wraparound);
    RUN_TEST(test_schedule_period_is_25);
    RUN_TEST(test_counter_next_sequence_and_wrap);
    RUN_TEST(test_slot_type_mapping);
    RUN_TEST(test_encode_slot_matches_reference_bytes);
    RUN_TEST(test_message_header_type_and_version);
    RUN_TEST(test_service_data_frame);
    RUN_TEST(test_service_data_frame_full_payload);
    RUN_TEST(test_adv_frame_on_air_constants);
    RUN_TEST(test_adv_frame_carries_the_service_data);
    RUN_TEST(test_adv_frame_full_payload);
    RUN_TEST(test_populate_identity_sets_fields);
    RUN_TEST(test_populate_identity_empty_strings_leave_defaults);
    RUN_TEST(test_populate_identity_overlong_strings_ignored);
    RUN_TEST(test_populate_identity_overlong_op_id_ignored);
    RUN_TEST(test_populate_identity_overlong_ua_desc_ignored);
    RUN_TEST(test_populate_identity_max_length_strings);
    RUN_TEST(test_populate_identity_max_length_op_id_and_desc);
    RUN_TEST(test_populate_identity_fields_are_independent);
    RUN_TEST(test_update_setters);
    RUN_TEST(test_encode_slot_rejects_out_of_range_direction);
    RUN_TEST(test_encode_slot_rejects_out_of_range_height);
    RUN_TEST(test_encode_slot_rejects_out_of_range_altitude);
    RUN_TEST(test_encode_slot_unknown_sentinels_encode);
    RUN_TEST(test_transmit_gating_schedule_and_counters);
    RUN_TEST(test_transmit_skips_unencodable_slot);
    RUN_TEST(test_encode_decode_round_trip);
    return UNITY_END();
}
