import { describe, test, expect } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import zlib from 'node:zlib';

import { wrap } from '../../wrap.js';

function writeInputs(html, script) {
  const dir = mkdtempSync(join(tmpdir(), 'dash-wrap-'));
  writeFileSync(join(dir, 'index.html'), html);
  writeFileSync(join(dir, 'bundle.js'), script);
  return {
    htmlPath: join(dir, 'index.html'),
    scriptPath: join(dir, 'bundle.js'),
    headerPath: join(dir, 'dash.h'),
    codePath: join(dir, 'dash.cpp'),
  };
}

describe('wrap', () => {
  test('emits the gzip array and a header declaring its length', () => {
    const paths = writeInputs('<html>%%%SCRIPT%%%</html>', 'console.log(1)');
    const { length, combinedCompressed } = wrap(paths);

    expect(length).toBe(combinedCompressed.length);

    const header = readFileSync(paths.headerPath, 'utf8');
    expect(header).toBe(
      '// Generated by dash/wrap.js - do not edit.\n' +
      '#include <Arduino.h>\n\n' +
      `extern const uint8_t DASH[${length}];`,
    );

    const code = readFileSync(paths.codePath, 'utf8');
    const bytes = code.match(/const uint8_t DASH\[(\d+)\] PROGMEM = \{ ([0-9a-fA-FxX, ]+) \};/);
    expect(bytes).not.toBeNull();
    expect(Number(bytes[1])).toBe(length);
    // The emitted array is exactly the gzip payload.
    expect(Buffer.from(bytes[2].split(', ').map(Number))).toEqual(combinedCompressed);
  });

  test('round-trips: the served bytes gunzip to the page with the script inlined', () => {
    // The script deliberately contains '$&' - a special replacement pattern
    // that String.replace would expand if the replacer were not a function.
    const script = 'alert("$&$1$`babel");\n//# sourceMappingURL=bundle.js.map';
    const html = '<!doctype html><html><head></head><body><div id="root"></div><script>%%%SCRIPT%%%</script></body></html>';
    const paths = writeInputs(html, script);
    const { combinedCompressed } = wrap(paths);

    expect(zlib.gunzipSync(combinedCompressed).toString('utf8')).toBe(
      html.replace('%%%SCRIPT%%%', () => script),
    );
  });
});
