title: "DRIFT"
description: "Drone Remote Identification and Flight Tracking"
url: "https://drift.wnagele.com"
baseurl: "/"
nav_external_links:
  - title: Releases
    url: https://github.com/wnagele/drift/releases
    hide_icon: true
    opens_in_new_tab: true
  - title: Source
    url: https://github.com/wnagele/drift
    hide_icon: true
    opens_in_new_tab: true
theme: just-the-docs
color_scheme: dark
callouts:
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: purple