const fs = require('fs');
const zlib = require('zlib');

// Wraps the webpack bundle into the firmware-served dash: the bundle is
// substituted into index.html's %%%SCRIPT%%% marker, the result is
// gzipped and emitted as the DASH[] PROGMEM array in dash.cpp/dash.h.
//
// Exported for the unit test (dash/src/__tests__/wrap.test.js); run as a
// script (dash/build.sh) it wraps the default files.
function wrap({ htmlPath, scriptPath, headerPath, codePath }) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  const script = fs.readFileSync(scriptPath, 'utf8');
  // The replacer must be a function: the bundle may contain '$&' and other
  // special replacement patterns that String.replace would otherwise expand.
  const combined = html.replace('%%%SCRIPT%%%', () => script);
  const combinedCompressed = zlib.gzipSync(Buffer.from(combined, 'utf8'));

  const length = combinedCompressed.length;
  const bytesNum = Array.from(combinedCompressed).join(', ');

  const generatedComment = '// Generated by dash/wrap.js - do not edit.\n';

  const headerContent = generatedComment + `#include <Arduino.h>\n\nextern const uint8_t DASH[${length}];`;
  fs.writeFileSync(headerPath, headerContent, 'utf8');

  const codeContent = generatedComment + `#include "dash.h"\n\nconst uint8_t DASH[${length}] PROGMEM = { ${bytesNum} };`;
  fs.writeFileSync(codePath, codeContent, 'utf8');

  return { length, combined, combinedCompressed };
}

if (require.main === module) {
  wrap({
    htmlPath: 'index.html',
    scriptPath: 'bundle.js',
    headerPath: 'dash.h',
    codePath: 'dash.cpp',
  });
}

module.exports = { wrap };
