name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Debug Info
        env:
          DEBUG_VERSION: ${{ github.ref_name }}
          DEBUG_GITREF: ${{ github.sha }}
        run: |
          sed -i "1s/^/#define DEBUG_VERSION \"${DEBUG_VERSION}\"\n/" src/debug.h
          sed -i "1s/^/#define DEBUG_GITREF \"${DEBUG_GITREF}\"\n/" src/debug.h
          grep '^#define DEBUG_' src/debug.h
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Install esptool
        run: pip install --upgrade esptool
      - name: Build
        run: pio run -e esp32_c3_devkit
      - name: Package
        run: |
          mkdir .pio/package
          esptool.py --chip esp32c3 \
                     merge_bin \
                     -o .pio/package/firmware-esp32_c3_devkit-${{ github.ref_name }}-full.bin \
                     0x0000 .pio/build/esp32_c3_devkit/bootloader.bin \
                     0x8000 .pio/build/esp32_c3_devkit/partitions.bin \
                     0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
                     0x10000 .pio/build/esp32_c3_devkit/firmware.bin
          cp .pio/build/esp32_c3_devkit/firmware.bin .pio/package/firmware-esp32_c3_devkit-${{ github.ref_name }}-ota.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            .pio/package/*.bin