name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Build
        run: pio run -e esp32_c3_devkit
      - name: Package
        run: |
          mkdir .pio/package
          mv .pio/build/esp32_c3_devkit/firmware.bin .pio/package/firmware-esp32_c3_devkit-${{ github.ref_name }}.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            .pio/package/*.bin